export const INIT_LOGIN = 'INIT_LOGIN';
export const LOGIN_FINISHED = 'LOGIN_FINISHED';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const REQUEST_LOAD_DEBTORS = 'REQUEST_LOAD_DEBTORS';
export const LOAD_DEBTORS = 'LOAD_DEBTORS';
