export const CHECKING_BOX = 'CHECKING_BOX';
export const ADDING_TO_CART = 'ADDING_TO_CART';
export const LOADING_INVENTORY = 'LOADING_INVENTORY';
export const ADDING_TO_BOX = 'ADDING_TO_BOX';
export const CUSTOM_BOX_ADDING_TO_BOX = 'CUSTOM_BOX_ADDING_TO_BOX ';
