version: 2
jobs:
  build:
    branches:
      only:
        - master
        - /rc-.*/
    docker:
      - image: circleci/node:9.11.2
    steps:
      - checkout # special step to check out source code to working directory
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: # run coverage report
          name: build
          command: npm run build
      - run: # run coverage report
          name: install sbx
          command: 'sudo npm install -g sbxcloud-cli'
      - run: # run coverage report
          name: deploy sbx
          command: sbxcloud-cli deploy ./build ff4de994-def8-4f46-9d76-67bbdb41c517 181 --username=carlosdelosreyes --password=$password --confirmation
